name: Frontend Release PR

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  frontend-release-pr:
    concurrency:
      group: frontend-release-pr-${{ github.ref }}
      cancel-in-progress: true

    name: generate frontend changelog
    runs-on: ubuntu-latest
    if: github.repository == 'codemonkey800/cryoet-data-portal'
    steps:
      - name: create changelog
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          # TODO Configuring using manifest file as workaround until we move the frontend to its own repo
          config-file: release-please.config.json
          manifest-file: release-please.manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}
